// Code generated by apiregister-gen. DO NOT EDIT.

package install

import (
	"gopath/src/pet-project/pkg/apis/petproject"
	v1 "gopath/src/pet-project/pkg/apis/petproject/v1"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

func init() {
	Install(builders.Scheme)
}

func Install(scheme *runtime.Scheme) {
	utilruntime.Must(v1.AddToScheme(scheme))
	utilruntime.Must(petproject.AddToScheme(scheme))
	utilruntime.Must(addKnownTypes(scheme))
}

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(petproject.SchemeGroupVersion,
		&petproject.Actor{},
		&petproject.ActorList{},
	)
	return nil
}
