// Code generated by apiregister-gen. DO NOT EDIT.

package apis

import (
	"gopath/src/pet-project/pkg/apis/petproject"
	_ "gopath/src/pet-project/pkg/apis/petproject/install" // Install the petproject group
	petprojectv1 "gopath/src/pet-project/pkg/apis/petproject/v1"

	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		petprojectv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetPetprojectAPIBuilder(),
	}
}

var petprojectApiGroup = builders.NewApiGroupBuilder(
	"petproject.shevchenkovitalii.com",
	"gopath/src/pet-project/pkg/apis/petproject").
	WithUnVersionedApi(petproject.ApiVersion).
	WithVersionedApis(
		petprojectv1.ApiVersion,
	).
	WithRootScopedKinds()

func GetPetprojectAPIBuilder() *builders.APIGroupBuilder {
	return petprojectApiGroup
}
