// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	petproject "gopath/src/pet-project/pkg/apis/petproject"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Actor)(nil), (*petproject.Actor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Actor_To_petproject_Actor(a.(*Actor), b.(*petproject.Actor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petproject.Actor)(nil), (*Actor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petproject_Actor_To_v1_Actor(a.(*petproject.Actor), b.(*Actor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ActorList)(nil), (*petproject.ActorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ActorList_To_petproject_ActorList(a.(*ActorList), b.(*petproject.ActorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petproject.ActorList)(nil), (*ActorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petproject_ActorList_To_v1_ActorList(a.(*petproject.ActorList), b.(*ActorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ActorSpec)(nil), (*petproject.ActorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ActorSpec_To_petproject_ActorSpec(a.(*ActorSpec), b.(*petproject.ActorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petproject.ActorSpec)(nil), (*ActorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petproject_ActorSpec_To_v1_ActorSpec(a.(*petproject.ActorSpec), b.(*ActorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ActorStatus)(nil), (*petproject.ActorStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ActorStatus_To_petproject_ActorStatus(a.(*ActorStatus), b.(*petproject.ActorStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petproject.ActorStatus)(nil), (*ActorStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petproject_ActorStatus_To_v1_ActorStatus(a.(*petproject.ActorStatus), b.(*ActorStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Actor_To_petproject_Actor(in *Actor, out *petproject.Actor, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ActorSpec_To_petproject_ActorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ActorStatus_To_petproject_ActorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Actor_To_petproject_Actor is an autogenerated conversion function.
func Convert_v1_Actor_To_petproject_Actor(in *Actor, out *petproject.Actor, s conversion.Scope) error {
	return autoConvert_v1_Actor_To_petproject_Actor(in, out, s)
}

func autoConvert_petproject_Actor_To_v1_Actor(in *petproject.Actor, out *Actor, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_petproject_ActorSpec_To_v1_ActorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_petproject_ActorStatus_To_v1_ActorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_petproject_Actor_To_v1_Actor is an autogenerated conversion function.
func Convert_petproject_Actor_To_v1_Actor(in *petproject.Actor, out *Actor, s conversion.Scope) error {
	return autoConvert_petproject_Actor_To_v1_Actor(in, out, s)
}

func autoConvert_v1_ActorList_To_petproject_ActorList(in *ActorList, out *petproject.ActorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]petproject.Actor)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ActorList_To_petproject_ActorList is an autogenerated conversion function.
func Convert_v1_ActorList_To_petproject_ActorList(in *ActorList, out *petproject.ActorList, s conversion.Scope) error {
	return autoConvert_v1_ActorList_To_petproject_ActorList(in, out, s)
}

func autoConvert_petproject_ActorList_To_v1_ActorList(in *petproject.ActorList, out *ActorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Actor)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_petproject_ActorList_To_v1_ActorList is an autogenerated conversion function.
func Convert_petproject_ActorList_To_v1_ActorList(in *petproject.ActorList, out *ActorList, s conversion.Scope) error {
	return autoConvert_petproject_ActorList_To_v1_ActorList(in, out, s)
}

func autoConvert_v1_ActorSpec_To_petproject_ActorSpec(in *ActorSpec, out *petproject.ActorSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Surname = in.Surname
	return nil
}

// Convert_v1_ActorSpec_To_petproject_ActorSpec is an autogenerated conversion function.
func Convert_v1_ActorSpec_To_petproject_ActorSpec(in *ActorSpec, out *petproject.ActorSpec, s conversion.Scope) error {
	return autoConvert_v1_ActorSpec_To_petproject_ActorSpec(in, out, s)
}

func autoConvert_petproject_ActorSpec_To_v1_ActorSpec(in *petproject.ActorSpec, out *ActorSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Surname = in.Surname
	return nil
}

// Convert_petproject_ActorSpec_To_v1_ActorSpec is an autogenerated conversion function.
func Convert_petproject_ActorSpec_To_v1_ActorSpec(in *petproject.ActorSpec, out *ActorSpec, s conversion.Scope) error {
	return autoConvert_petproject_ActorSpec_To_v1_ActorSpec(in, out, s)
}

func autoConvert_v1_ActorStatus_To_petproject_ActorStatus(in *ActorStatus, out *petproject.ActorStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ActorStatus_To_petproject_ActorStatus is an autogenerated conversion function.
func Convert_v1_ActorStatus_To_petproject_ActorStatus(in *ActorStatus, out *petproject.ActorStatus, s conversion.Scope) error {
	return autoConvert_v1_ActorStatus_To_petproject_ActorStatus(in, out, s)
}

func autoConvert_petproject_ActorStatus_To_v1_ActorStatus(in *petproject.ActorStatus, out *ActorStatus, s conversion.Scope) error {
	return nil
}

// Convert_petproject_ActorStatus_To_v1_ActorStatus is an autogenerated conversion function.
func Convert_petproject_ActorStatus_To_v1_ActorStatus(in *petproject.ActorStatus, out *ActorStatus, s conversion.Scope) error {
	return autoConvert_petproject_ActorStatus_To_v1_ActorStatus(in, out, s)
}
