// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "gopath/src/pet-project/pkg/apis/petproject/v1"
	scheme "gopath/src/pet-project/pkg/client/clientset_generated/clientset/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ActorsGetter has a method to return a ActorInterface.
// A group's client should implement this interface.
type ActorsGetter interface {
	Actors(namespace string) ActorInterface
}

// ActorInterface has methods to work with Actor resources.
type ActorInterface interface {
	Create(*v1.Actor) (*v1.Actor, error)
	Update(*v1.Actor) (*v1.Actor, error)
	UpdateStatus(*v1.Actor) (*v1.Actor, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Actor, error)
	List(opts metav1.ListOptions) (*v1.ActorList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Actor, err error)
	ActorExpansion
}

// actors implements ActorInterface
type actors struct {
	client rest.Interface
	ns     string
}

// newActors returns a Actors
func newActors(c *PetprojectV1Client, namespace string) *actors {
	return &actors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the actor, and returns the corresponding actor object, and an error if there is any.
func (c *actors) Get(name string, options metav1.GetOptions) (result *v1.Actor, err error) {
	result = &v1.Actor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("actors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Actors that match those selectors.
func (c *actors) List(opts metav1.ListOptions) (result *v1.ActorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ActorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("actors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested actors.
func (c *actors) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("actors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a actor and creates it.  Returns the server's representation of the actor, and an error, if there is any.
func (c *actors) Create(actor *v1.Actor) (result *v1.Actor, err error) {
	result = &v1.Actor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("actors").
		Body(actor).
		Do().
		Into(result)
	return
}

// Update takes the representation of a actor and updates it. Returns the server's representation of the actor, and an error, if there is any.
func (c *actors) Update(actor *v1.Actor) (result *v1.Actor, err error) {
	result = &v1.Actor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("actors").
		Name(actor.Name).
		Body(actor).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *actors) UpdateStatus(actor *v1.Actor) (result *v1.Actor, err error) {
	result = &v1.Actor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("actors").
		Name(actor.Name).
		SubResource("status").
		Body(actor).
		Do().
		Into(result)
	return
}

// Delete takes name of the actor and deletes it. Returns an error if one occurs.
func (c *actors) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("actors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *actors) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("actors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched actor.
func (c *actors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Actor, err error) {
	result = &v1.Actor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("actors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
