// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "gopath/src/pet-project/pkg/apis/petproject/v1"
	"gopath/src/pet-project/pkg/client/clientset_generated/clientset/scheme"

	rest "k8s.io/client-go/rest"
)

type PetprojectV1Interface interface {
	RESTClient() rest.Interface
	ActorsGetter
}

// PetprojectV1Client is used to interact with features provided by the petproject.shevchenkovitalii.com group.
type PetprojectV1Client struct {
	restClient rest.Interface
}

func (c *PetprojectV1Client) Actors(namespace string) ActorInterface {
	return newActors(c, namespace)
}

// NewForConfig creates a new PetprojectV1Client for the given config.
func NewForConfig(c *rest.Config) (*PetprojectV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &PetprojectV1Client{client}, nil
}

// NewForConfigOrDie creates a new PetprojectV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *PetprojectV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new PetprojectV1Client for the given RESTClient.
func New(c rest.Interface) *PetprojectV1Client {
	return &PetprojectV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *PetprojectV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
