// Code generated by lister-gen. DO NOT EDIT.

package v1

// ActorListerExpansion allows custom methods to be added to
// ActorLister.
type ActorListerExpansion interface{}

// ActorNamespaceListerExpansion allows custom methods to be added to
// ActorNamespaceLister.
type ActorNamespaceListerExpansion interface{}
